### ISSUE TITLE
Fall 2021 website updates

### ISSUE THREAD

**Issue by jacob14916** [uclaacm/icpc-website#93]
- [x] Update all the events and delete old ones that are no longer upcoming
- [x] Update officer bios
- [x] Delete retired officers
- [x] Update Regionals page with tryouts information
- [x] Rearrange the home page: put upcoming events at the top and merge the redundant "who we are" and "what we do" sections

**Comment by gu-ana** [comment]
Retired officers are taken out. 
I had updated the events to what I know as of right now(Beginner track and Interview Track). 
I need to add in more people that have filled out officer bio updates.
I need tryout information, will ask you over messenger.
Will take out the redundant stuff on home page.
