### ISSUE TITLE
Mistaken word in CodeSprint LA website

### ISSUE THREAD

**Issue by ManuelLoaizaVasquez** [uclaacm/icpc-website#94]
In the CodeSprint LA 2021 webpage (which I think its repository is private), the text inside the enclosed `button` must say `Open Team Round`.
![image](https://user-images.githubusercontent.com/19366788/133936966-fae0aa60-e60e-4d52-a137-69b1e49d0269.png)

**Comment by TonyXia2001** [comment]
Thanks for letting us know!
